{{ template "<%= projectName %>.validateHosts" . }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "<%= projectName %>.fullname" . }}-<%= apiName %>
  labels:
    app: {{ template "<%= projectName %>.name" . }}
    component: <%= apiName %>
    chart: {{ template "<%= projectName %>.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  {{- range .Values.api.hosts }}
  - {{ . -}}
  {{ end }}
  gateways:
  - {{ required "Value api.gateway is required" .Values.api.gateway }}
  http:
  - match:
      - uri:
          prefix: {{ required "Value api.routePrefix is required" .Values.api.routePrefix }}
    rewrite:
      uri: /external/
    route:
      - destination:
          port:
            number: 80
          host: {{ template "<%= projectName %>.fullname" . }}-<%= apiName %>
